# Generated by Django 4.1.4 on 2022-12-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_App', '0002_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='client',
            new_name='selectClient',
        ),
    ]
