# Generated by Django 4.1.4 on 2023-01-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_App', '0004_goals_datecreated_goals_goalenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='goalStatus',
            field=models.CharField(blank=True, choices=[('c', 'complete'), ('x', 'notcomplete')], default='x', max_length=1),
        ),
        migrations.AddField(
            model_name='goals',
            name='goals',
            field=models.BooleanField(default=False),
        ),
    ]
