# Generated by Django 4.1.4 on 2023-01-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_App', '0005_goals_goalstatus_goals_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='goalStatus',
            field=models.CharField(choices=[('c', 'complete'), ('x', 'notcomplete')], max_length=1),
        ),
    ]
