# Generated by Django 4.1.4 on 2023-01-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_App', '0007_remove_goals_goalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='goalStatus',
            field=models.CharField(blank=True, choices=[('c', 'complete'), ('x', 'notcomplete')], max_length=1),
        ),
    ]
