# Generated by Django 4.1.4 on 2023-01-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_App', '0008_goals_goalstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='goalStatus',
        ),
    ]
